# Generated by Django 4.1.7 on 2023-02-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestbook", options={"verbose_name_plural": "Guest Book"},
        ),
    ]
