# Generated by Django 4.1.7 on 2023-02-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_guestbook_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="guestbook", name="deleted_at",),
        migrations.RemoveField(model_name="guestbook", name="is_deleted",),
    ]
